Repository mergifyio-testing/functional-testing-repo-Zerdanes, pull requests merged in 2021-09, with the labels that each got.

#551 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#552 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#558 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#561 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#566 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#606 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#607 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#613 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready
